### ISSUE TITLE
Source of application?

### ISSUE THREAD

**Issue by a-schild** [ChrisRfr/PinUtil#1]
Hello,

any chance to also have the source of the executables?
It would help to be sure that's not malware and/or adapt it to new requirements.

Thanks

**Comment by ChrisRfr** [comment]
I'm not sure it's a good idea to share the source.
Microsoft has several times changed the process to avoid the use, they really wan't to prevent us doing this in code...
If there are too many tools, software that uses, they will further strengthen the protection.

For the explanation of what is done, PinUtil uses MasqueradePEB Procedure to gives the appearance of **explorer.exe** process and so the "pin to taskbar" item will show up in context menu, bypassing MS trick To hide it.
Idea from [PowerShell-Suite Masquerade-PEB.ps1](https://github.com/FuzzySecurity/PowerShell-Suite/blob/master/Masquerade-PEB.ps1)

Then it uses the IID_IContextMenu to Invoke the Context Menu for the File and Browse the Menu Items
If the Name Matches the "pin to taskbar" Verb, the Associate Command is Called

Microsoft prefer to do it this way: [Pin your app to the taskbar](https://docs.microsoft.com/en-us/windows/uwp/design/shell/pin-to-taskbar)

**Comment by a-schild** [comment]
Thanks, not ideal but probably the safe way to do it.
